CREATE DATABASE IF NOT EXISTS `{DB_NAME}` DEFAULT CHARACTER SET utf8 collate utf8_general_ci;
USE `{DB_NAME}`;

DROP TABLE IF EXISTS `{TABLE_PREFIX}admins`;
CREATE TABLE `{TABLE_PREFIX}admins` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `login` varchar(20) DEFAULT NULL,
  `password` varchar(32) DEFAULT NULL,
  `level` varchar(25) DEFAULT NULL,
  `reset_hash` varchar(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

INSERT INTO `{TABLE_PREFIX}admins` (`id`, `login`, `password`, `level`, `reset_hash`) VALUES
(1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 'SUPERUSER', '');

DROP TABLE IF EXISTS `{TABLE_PREFIX}alerts`;
CREATE TABLE `{TABLE_PREFIX}alerts` (
  `alert_id` int(5) NOT NULL AUTO_INCREMENT,
  `code` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `approved` tinyint(1) NOT NULL,
  `keyword` varchar(1000) NOT NULL,
  `listing_type` int(11) NOT NULL,
  `property_type` int(11) NOT NULL,
  `style` int(11) NOT NULL,
  `from_price` int(11) NOT NULL,
  `to_price` int(11) NOT NULL,
  `location_1` int(5) NOT NULL,
  `location_2` int(5) NOT NULL,
  `location_3` int(5) NOT NULL,
  `zip` varchar(100) NOT NULL,
  `radius` smallint(3) NOT NULL,
  `bedrooms` tinyint(2) NOT NULL,
  `bathrooms` tinyint(2) NOT NULL,
  `half_bathrooms` tinyint(2) NOT NULL,
  `year_built` int(4) NOT NULL,
  `garage` int(5) NOT NULL,
  `garage_cars` int(5) NOT NULL,
  `basement` int(5) NOT NULL,
  `living_area` varchar(1000) NOT NULL,
  `lot_size` varchar(1000) NOT NULL,
  `amenities` varchar(1000) NOT NULL,
  `appliances` varchar(1000) NOT NULL,
  `features` varchar(1000) NOT NULL,
  `custom1` varchar(1000) NOT NULL,
  `custom2` varchar(1000) NOT NULL,
  `custom3` varchar(1000) NOT NULL,
  `custom4` varchar(1000) NOT NULL,
  `custom5` varchar(1000) NOT NULL,
  `custom6` varchar(1000) NOT NULL,
  `custom7` varchar(1000) NOT NULL,
  `custom8` varchar(1000) NOT NULL,
  `custom9` varchar(1000) NOT NULL,
  `custom10` varchar(1000) NOT NULL,
  PRIMARY KEY (`alert_id`),
  KEY `approved` (`approved`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}appliances`;
CREATE TABLE `{TABLE_PREFIX}appliances` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=22 ;

INSERT INTO `{TABLE_PREFIX}appliances` (`name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `id`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`) VALUES
('Dishwasher', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Wall Oven', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Range', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Disposal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Compactor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Microwave', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Indoor Grill', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Countertop Range', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Refrigerator', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Freezer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Washer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Dryer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Water Treatment', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Wine Storage', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Energy Star', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Water Softener', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Vent Hood', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Vacuum System', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `{TABLE_PREFIX}ban`;
CREATE TABLE `{TABLE_PREFIX}ban` (
  `name` varchar(50) DEFAULT NULL,
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}basement`;
CREATE TABLE `{TABLE_PREFIX}basement` (
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

INSERT INTO `{TABLE_PREFIX}basement` (`name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `id`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`) VALUES
('Full', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Partial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Finished', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `{TABLE_PREFIX}buildings`;
CREATE TABLE `{TABLE_PREFIX}buildings` (
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

INSERT INTO `{TABLE_PREFIX}buildings` (`name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `id`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`) VALUES
('Barn / Stable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Boatlift', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Dock / Pier', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Gazebo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Greenhouse', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cabana', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kennel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Guest House', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `{TABLE_PREFIX}configuration`;
CREATE TABLE `{TABLE_PREFIX}configuration` (
  `name` varchar(50) DEFAULT NULL,
  `val` varchar(255) DEFAULT NULL,
  `descr` varchar(255) DEFAULT NULL,
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `{TABLE_PREFIX}configuration` (`name`, `val`, `descr`) VALUES
('website_name_short', 'Real Estate Demo', 'The short name of your website for title tag'),
('website_name', 'Real Estate Web Site Demo - The Best Real Estate Website', 'The name of your website'),
('title_meta', 'RealtyScript - Real Estate Web Site Demo - The Best Real Estate Website', 'Global template meta title'),
('description_meta', 'RealtyScript Demo is The Best Real Estate Website', 'Global template meta keywords'),
('keywords_meta', 'php, sql, mysql, script, real, estate, immovable property, directory', 'Global template meta keywords'),
('robots_meta', 'index, follow', 'Global template meta robots'),
('general_e_mail', 'demo@localhost', 'Default FROM e-mail address to send messages to the users'),
('general_e_mail_name', 'RealtyScript Demo', 'Default FROM name to send messages to the users'),
('language', 'english', 'Default language name'),
('template', 'responsive', 'Default template name'),
('latitude', '42.3583333', 'The latitude coordinates in which the office/site owner resides. Used primarily for the "contact" page map.'),
('rewrite', 'ON', 'Enable mod_rewrite Apache module support for better SEO (ON/OFF)'),
('timings', 'OFF', 'Enable debug information in the bottom of each page'),
('currency', '$', 'Default currency'),
('approve_realtors', 'OFF', 'Shall administrator approve new realtors or add them into the database automatically (ON/OFF).'),
('approve_listings', 'OFF', 'Shall administrator approve new listings or add them into the database automatically (ON/OFF).'),
('max_number_of_listings', '99', 'Maximum Number of Listings allowed for each realtor.'),
('max_number_of_photos', '99', 'Maximum Number of images per listing in Photo Gallery allowed for each realtor.'),
('new_days', '5', 'Will keep listing NEW during this number of days.'),
('updated_days', '5', 'Will keep listing UPDATED during this number of days.'),
('featured_limit', '6', 'Number of listing to show in the featured listings module'),
('most_visited_limit', '4', 'Number of listing to show in the most visited listings module'),
('recent_limit', '4', 'Number of listing to show in the recent listings module'),
('visited_limit', '3', 'Number of Recently Visited Listings to store and show'),
('search_results', '12', 'Number of listing to show per page in the search section'),
('search_description', '150', 'Number of characters per description to show in the search results'),
('realtor_description_size', '2500', 'Size of a Realtor Description Field.'),
('listing_description_size', '2500', 'Size of a Listing Description Field.'),
('listing_directions_size', '500', 'Size of a Listing Directions Field.'),
('gallery_description_size', '500', 'Size of a Photo Gallery Description Field.'),
('mailer_message_size', '200', 'Maximum size of a message sent to a user via mailer.'),
('photo_resampled_width', '150', 'Resize a Realtor photo to this width (pixels).'),
('image_resampled_width', '150', 'Resize a listing main image to this width (pixels).'),
('gallery_resampled_width', '150', 'Resize a listing photo gallery image to this width (pixels).'),
('gallery_window_width', '660', 'Photo Gallery full size image window width (pixels).'),
('gallery_window_height', '550', 'Photo Gallery full size image window height (pixels).'),
('list_background_color_even', '#F1F1F1', 'Background color for all even search results listings cells'),
('price_range_min', '1', 'Search Form: Minimum Property Price Range'),
('price_range_max', '1000000', 'Search Form: Maximum Property Price Range'),
('price_range_step', '50000', 'Search Form: Property Price Range Step'),
('map_value', 'a', 'Specifies whether to rely on the lat/long coordinates or the address when placing a marker on a map (a - address, c - coordinates)'),
('paypal_email', 'me@domain.com', 'Your PRIMARY paypal email address'),
('paypal_currency', 'USD', 'Paypal currency, USD, GBP etc.'),
('2co_user_id', '', '2co User ID'),
('2co_secret_word', '', '2co Secret Word'),
('2co_gateway', 'https://www2.2checkout.com/2co/buyer/purchase', '2co Default Gateway URL'),
('gateway', '1', 'Default Payment Gateway (1 for PayPal, 2 for 2checkout)'),
('longitude', '-71.0602778', 'The longitude coordinates in which the office/site owner resides. Used primarily for the "contact" page map.'),
('free_listings', '50', 'Free Agent Package Number of Listings Allowed'),
('free_gallery', '5', 'Free Agent Package Number of Photo Gallery Images Allowed'),
('free_mainimage', 'ON', 'Free Agent Package Show Main Property Image (ON/OFF)'),
('free_photo', 'ON', 'Free Agent Package Show Agent Photo/Logo (ON/OFF)'),
('free_phone', 'ON', 'Free Agent Package Show Agent Phone/Fax/Mobile (ON/OFF)'),
('free_address', 'ON', 'Free Agent Package Show Agent and Property Address (ON/OFF)'),
('quick_search', 'ON', 'Enable or disable the ''Quick Search'' from displaying on the left-hand side of the site (ON/OFF)'),
('featured_listings', 'ON', 'Enable or disable featured listings from displaying on the index page (ON/OFF)'),
('all_listings', 'ON', 'Enable or disable showing all listings, not just featured, randomly on the index page (ON/OFF)'),
('recent_listings', 'ON', 'Enable or disable recent listings/agents and most visited listings on the index page at the bottom of the page (ON/OFF)'),
('main_search', 'ON', 'Enable or disable the main search (WHAT / WHERE / OPTIONS) at the top of the index page (ON/OFF)'),
('main_map', 'ON', 'Enable or disable the map from appearing on the index page (Must have Google Maps API key installed in order to show) (ON/OFF)'),
('featured_agents', 'OFF', 'Enable or disable featured agents from displaying on the index page (ON/OFF)'),
('settings_box', 'ON', 'Enable or disable the ''Settings'' box from displaying with Language/Template options (ON/OFF)'),
('online_box', 'ON', 'Enable or disable the ''Online'' box from displaying with logged-in agents currently online (ON/OFF)'),
('all_agents', 'OFF', 'Enable or disable showing all agents, not just featured, randomly on the index page (ON/OFF)'),
('expired_listings', '1', 'What should happen to listings that have expired? (1 - Disable Listing, 2 - Delete Listing)'),
('contact_agents', '1', 'Specify who has access to listing contact information. (1 - Everyone, 2 - Registered account holders only, 3 - Paid account holders only)'),
('slideshow_main', 'ON', 'Enable or disable the ''Slideshow'' box from displaying on the main page (ON/OFF)'),
('slideshow_type', '1', 'Specify whether the slideshow should grab all listings or featured listings only (1 - Featured only (random), 2 - All listings (random))'),
('slideshow_speed', '5000', 'Specify the slideshow scroll speed. Note: This is in milliseconds (5000 = 5 seconds. 10000 = 10 seconds)'),
('slideshow_visibility', '4', 'Specify how many properties should be visible in the slideshow at a time'),
('map_zoom', '12', 'Specify how zoomed out the map should be on pages that have a map. (1 - zoomed in all the way. 10 - zoomed out all the way. Can be anything from 1 - 10.'),
('map_height', '400', 'Specify the Google Map height on all pages that have a map. (E.g., 400 - 400 pixels wide'),
('map_width', '500', 'Specify the Google Map width on all pages that have a map. (E.g., 500 - 500 pixels in height'),
('expire_notice', '5', 'Specify the number of days in advance a seller should be e-mailed that their package is going to expire (5 - 5 days, 14 - 2 weeks'),
('show_calendar', 'OFF', 'Enable or disable showing the availability calendar (ON/OFF'),
('show_mls', 'ON', 'Enable or disable showing the MLS field (ON/OFF)'),
('show_postal_code', 'ON', 'Enable or disable showing the ZIP code field (ON/OFF)'),
('paypal_mode', 'LIVE', 'Production PayPal payment gateway (LIVE) or the sandbox test environment (TEST).'),
('free_listings_expire', '0', 'Number of days after which a free listing expires.'),
('slideshow_limit', '25', 'Number of listings to show in the slideshow module'),
('allow_same_title', 'OFF', 'Allow duplicate listing property titles (ON/OFF)'),
('allow_same_e_mail', 'OFF', 'Allow multiple accounts with same e-mail address (ON/OFF)'),
('price_monthly_range_min', '0', 'Search Form: Minimum Monthly Rental Price Range'),
('price_monthly_range_max', '10000', 'Search Form: Maximum Monthly Rental Price Range'),
('price_monthly_range_step', '500', 'Search Form: Monthly Rental Price Range Step'),
('decimal_point', '.', 'Character to use as decimal point (number formatting)'),
('1000_separator', ',', 'Character to use as thousands separator (number formatting)'),
('contact_phone', '555-444-3333', 'Site phone number'),
('address1', '123 Main St.', 'Address of the site owner''s office.'),
('city', 'Boston', 'City of the site owner''s office.'),
('state', 'MA', 'State of the site owner''s office.'),
('country', 'United States', 'Country of the site owner''s office.'),
('phone', '555-444-3333', 'Site owner''s phone number'),
('site_mode', '2', '1 - The web site will run in agent mode, which is optimized for a sole agent or an office. 2 - The site runs in portal mode, which is similar to Zillow.com and other for sale by owner realty web sites. Features such as packages, etc. will be available.'),
('facebook_url', 'Test', 'URL of Facebook page if it exists'),
('flickr_url', 'Test', 'URL of Flickr page if it exists'),
('google_url', 'Test', 'Google+ URL if it exists'),
('linkedin_url', 'Test', 'LinkedIN URL if it exists'),
('twitter_url', 'Test', 'Twitter URL if it exists'),
('vimeo_url', 'Test', 'Vimeo URL if it exists'),
('skype', 'test.skype', 'Skype username if it exists'),
('contact_address', 'PO Box 123', 'Postal Address'),
('share_this', '0af1cddf-b260-40b8-b5e3-45c6eef36ce3', 'This is your ShareThis account ID. Sign up at <a href=http://www.sharethis.com target=_blank>ShareThis.com</a>.'),
('captcha_private_key', '', 'Captcha private key from Google reCAPTCHA: https://www.google.com/recaptcha'),
('captcha_public_key', '', 'Captcha public key from Google reCAPTCHA: https://www.google.com/recaptcha'),
('captcha_status', 'OFF', 'Enable or disable reCAPTCHA to protect against spam.'),
('allow_registration', 'ON', 'Enable or disable the ability for user\'s to register for an account.')
;

DROP TABLE IF EXISTS `{TABLE_PREFIX}cron`;
CREATE TABLE `{TABLE_PREFIX}cron` (
  `counter` int(15) unsigned DEFAULT '0',
  `time` bigint(15) unsigned DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `{TABLE_PREFIX}featured`;
CREATE TABLE `{TABLE_PREFIX}featured` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `featured` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `package` int(10) unsigned DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}featured_agents`;
CREATE TABLE `{TABLE_PREFIX}featured_agents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `featured` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `package` int(10) unsigned DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}features`;
CREATE TABLE `{TABLE_PREFIX}features` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

INSERT INTO `{TABLE_PREFIX}features` (`name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `id`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`) VALUES
('9 ft Ceilings', '', '', '', '9 aukštas', '', '', '', '', '', '', '', 1, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
('Beamed Ceilings', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cathedral Ceilings', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Bay / Bow Windows', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Breakfast Nook', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `{TABLE_PREFIX}fields`;
CREATE TABLE `{TABLE_PREFIX}fields` (
  `id` mediumint(5) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `type` enum('select','input','textarea') NOT NULL,
  `name2` varchar(255) NOT NULL,
  `name3` varchar(255) NOT NULL,
  `name4` varchar(255) NOT NULL,
  `name5` varchar(255) NOT NULL,
  `name6` varchar(255) NOT NULL,
  `name7` varchar(255) NOT NULL,
  `name8` varchar(255) NOT NULL,
  `name9` varchar(255) NOT NULL,
  `name10` varchar(255) NOT NULL,
  `name11` varchar(255) NOT NULL,
  `name12` varchar(255) NOT NULL,
  `name13` varchar(255) NOT NULL,
  `name14` varchar(255) NOT NULL,
  `name15` varchar(255) NOT NULL,
  `name16` varchar(255) NOT NULL,
  `name17` varchar(255) NOT NULL,
  `name18` varchar(255) NOT NULL,
  `name19` varchar(255) NOT NULL,
  `name20` varchar(255) NOT NULL,
  `name21` varchar(255) NOT NULL,
  `name22` varchar(255) NOT NULL,
  `name23` varchar(255) NOT NULL,
  `name24` varchar(255) NOT NULL,
  `name25` varchar(255) NOT NULL,
  `name26` varchar(255) NOT NULL,
  `name27` varchar(255) NOT NULL,
  `name28` varchar(255) NOT NULL,
  `name29` varchar(255) NOT NULL,
  `name30` varchar(255) NOT NULL,
  `field` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}gallery`;
CREATE TABLE `{TABLE_PREFIX}gallery` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `userid` int(10) unsigned DEFAULT '0',
  `listingid` int(10) unsigned DEFAULT '0',
  `temp_id` int(10) NOT NULL,
  `image_name` varchar(255) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `date_added` date DEFAULT NULL,
  `date_updated` date DEFAULT NULL,
  `ip_added` text,
  `ip_updated` text,
  PRIMARY KEY (`id`),
  KEY `userid` (`userid`),
  KEY `listingid` (`listingid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}garage`;
CREATE TABLE `{TABLE_PREFIX}garage` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;

INSERT INTO `{TABLE_PREFIX}garage` (`name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `id`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`) VALUES
('Detatched', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Attached', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Carport', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Other', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `{TABLE_PREFIX}listings`;
CREATE TABLE `{TABLE_PREFIX}listings` (
  `listing_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `userid` int(10) unsigned NOT NULL DEFAULT '0',
  `approved` tinyint(1) unsigned DEFAULT '0',
  `featured` varchar(1) NOT NULL DEFAULT 'B',
  `mls` varchar(10) DEFAULT NULL,
  `type` smallint(5) unsigned DEFAULT '0',
  `style` smallint(5) unsigned DEFAULT '0',
  `status` tinyint(1) unsigned DEFAULT '0',
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `size` varchar(50) DEFAULT NULL,
  `dimensions` varchar(50) DEFAULT NULL,
  `bedrooms` tinyint(2) unsigned DEFAULT '0',
  `bathrooms` tinyint(2) unsigned DEFAULT '0',
  `half_bathrooms` tinyint(2) unsigned DEFAULT '0',
  `garage` smallint(5) unsigned DEFAULT '0',
  `garage_cars` tinyint(2) unsigned DEFAULT '0',
  `basement` smallint(5) unsigned DEFAULT '0',
  `location_1` int(5) DEFAULT NULL,
  `location_2` int(5) NOT NULL,
  `location_3` int(5) NOT NULL,
  `zip` varchar(20) DEFAULT NULL,
  `address1` varchar(50) DEFAULT NULL,
  `address2` varchar(50) DEFAULT NULL,
  `display_address` char(3) DEFAULT NULL,
  `price` bigint(15) unsigned DEFAULT '0',
  `directions` text,
  `year_built` varchar(4) DEFAULT NULL,
  `buildings` varchar(255) DEFAULT NULL,
  `appliances` varchar(255) DEFAULT NULL,
  `features` varchar(255) DEFAULT NULL,
  `date_added` date DEFAULT NULL,
  `date_approved` date DEFAULT NULL,
  `date_updated` date DEFAULT NULL,
  `date_upgraded` date DEFAULT NULL,
  `ip_added` text,
  `ip_updated` text,
  `ip_upgraded` text,
  `hits` mediumint(8) unsigned DEFAULT '0',
  `image_uploaded` tinyint(1) unsigned DEFAULT '0',
  `video` varchar(255) DEFAULT NULL,
  `type2` smallint(5) unsigned DEFAULT '0',
  `calendar` text,
  `latitude` varchar(255) DEFAULT NULL,
  `longitude` varchar(255) DEFAULT NULL,
  `title2` text,
  `title3` text,
  `title4` text,
  `title5` text,
  `title6` text,
  `title7` text,
  `title8` text,
  `title9` text,
  `title10` text,
  `title11` text,
  `title12` text,
  `title13` text,
  `title14` text,
  `title15` text,
  `title16` text,
  `title17` text,
  `title18` text,
  `title19` text,
  `title20` text,
  `title21` text,
  `title22` text,
  `title23` text,
  `title24` text,
  `title25` text,
  `title26` text,
  `title27` text,
  `title28` text,
  `title29` text,
  `title30` text,
  `description2` text,
  `description3` text,
  `description4` text,
  `description5` text,
  `description6` text,
  `description7` text,
  `description8` text,
  `description9` text,
  `description10` text,
  `description11` text,
  `description12` text,
  `description13` text,
  `description14` text,
  `description15` text,
  `description16` text,
  `description17` text,
  `description18` text,
  `description19` text,
  `description20` text,
  `description21` text,
  `description22` text,
  `description23` text,
  `description24` text,
  `description25` text,
  `description26` text,
  `description27` text,
  `description28` text,
  `description29` text,
  `description30` text,
  `video2` varchar(255) DEFAULT NULL,
  `custom1` varchar(255) NOT NULL,
  `custom2` varchar(255) NOT NULL,
  `custom3` varchar(255) NOT NULL,
  `custom4` varchar(255) NOT NULL,
  `custom5` varchar(255) NOT NULL,
  `custom6` varchar(255) NOT NULL,
  `custom7` varchar(255) NOT NULL,
  `custom8` varchar(255) NOT NULL,
  `custom9` varchar(255) NOT NULL,
  `custom10` varchar(255) NOT NULL,
  PRIMARY KEY (`listing_id`),
  KEY `userid` (`userid`),
  FULLTEXT KEY `title` (`title`,`description`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5637 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}locations`;
CREATE TABLE `{TABLE_PREFIX}locations` (
  `location_id` int(5) NOT NULL AUTO_INCREMENT,
  `location_name` varchar(255) NOT NULL,
  `location_parent` int(5) NOT NULL,
  PRIMARY KEY (`location_id`),
  KEY `location_parent` (`location_parent`),
  KEY `location_name` (`location_name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}online`;
CREATE TABLE `{TABLE_PREFIX}online` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `time` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}packages`;
CREATE TABLE `{TABLE_PREFIX}packages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `price` varchar(255) DEFAULT NULL,
  `days` int(10) unsigned DEFAULT '0',
  `position` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

INSERT INTO `{TABLE_PREFIX}packages` (`id`, `name`, `price`, `days`, `position`) VALUES
(1, 'Bronze Package', '9.95', 30, '3'),
(2, 'Gold Package', '29.95', 90, '2'),
(3, 'Platinum Package', '99.95', 365, '1');

DROP TABLE IF EXISTS `{TABLE_PREFIX}packages_agents`;
CREATE TABLE `{TABLE_PREFIX}packages_agents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `price` varchar(255) DEFAULT NULL,
  `days` int(10) unsigned DEFAULT '0',
  `position` varchar(255) DEFAULT NULL,
  `listings` varchar(255) DEFAULT NULL,
  `gallery` varchar(255) DEFAULT NULL,
  `mainimage` varchar(255) DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

INSERT INTO `{TABLE_PREFIX}packages_agents` (`id`, `name`, `price`, `days`, `position`, `listings`, `gallery`, `mainimage`, `photo`, `phone`, `address`) VALUES
(1, 'Entry Level', '9.95', 30, '1', '10', 'ON', 'ON', 'ON', 'ON', 'ON'),
(2, 'Experienced', '29.95', 30, '2', '25', 'ON', 'ON', 'ON', 'ON', 'ON'),
(3, 'True Professional', '99.95', 30, '3', '100', 'ON', 'ON', 'ON', 'ON', 'ON');

DROP TABLE IF EXISTS `{TABLE_PREFIX}pages`;
CREATE TABLE `{TABLE_PREFIX}pages` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `menu` varchar(255) DEFAULT NULL,
  `text` text,
  `date` date DEFAULT NULL,
  `menu2` varchar(255) DEFAULT NULL,
  `menu3` varchar(255) DEFAULT NULL,
  `menu4` varchar(255) DEFAULT NULL,
  `menu5` varchar(255) DEFAULT NULL,
  `menu6` varchar(255) DEFAULT NULL,
  `menu7` varchar(255) DEFAULT NULL,
  `menu8` varchar(255) DEFAULT NULL,
  `menu9` varchar(255) DEFAULT NULL,
  `menu10` varchar(255) DEFAULT NULL,
  `menu11` varchar(255) DEFAULT NULL,
  `menu12` varchar(255) DEFAULT NULL,
  `menu13` varchar(255) DEFAULT NULL,
  `menu14` varchar(255) DEFAULT NULL,
  `menu15` varchar(255) DEFAULT NULL,
  `menu16` varchar(255) DEFAULT NULL,
  `menu17` varchar(255) DEFAULT NULL,
  `menu18` varchar(255) DEFAULT NULL,
  `menu19` varchar(255) DEFAULT NULL,
  `menu20` varchar(255) DEFAULT NULL,
  `menu21` varchar(255) DEFAULT NULL,
  `menu22` varchar(255) DEFAULT NULL,
  `menu23` varchar(255) DEFAULT NULL,
  `menu24` varchar(255) DEFAULT NULL,
  `menu25` varchar(255) DEFAULT NULL,
  `menu26` varchar(255) DEFAULT NULL,
  `menu27` varchar(255) DEFAULT NULL,
  `menu28` varchar(255) DEFAULT NULL,
  `menu29` varchar(255) DEFAULT NULL,
  `menu30` varchar(255) DEFAULT NULL,
  `text2` text,
  `text3` text,
  `text4` text,
  `text5` text,
  `text6` text,
  `text7` text,
  `text8` text,
  `text9` text,
  `text10` text,
  `text11` text,
  `text12` text,
  `text13` text,
  `text14` text,
  `text15` text,
  `text16` text,
  `text17` text,
  `text18` text,
  `text19` text,
  `text20` text,
  `text21` text,
  `text22` text,
  `text23` text,
  `text24` text,
  `text25` text,
  `text26` text,
  `text27` text,
  `text28` text,
  `text29` text,
  `text30` text,
  `status` enum('1','0') NOT NULL DEFAULT '1',
  `string` varchar(255) DEFAULT NULL,
  `navigation` enum('0','1') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=9 ;

INSERT INTO `{TABLE_PREFIX}pages` (`menu`, `text`, `date`, `id`, `menu2`, `menu3`, `menu4`, `menu5`, `menu6`, `menu7`, `menu8`, `menu9`, `menu10`, `menu11`, `menu12`, `menu13`, `menu14`, `menu15`, `menu16`, `menu17`, `menu18`, `menu19`, `menu20`, `menu21`, `menu22`, `menu23`, `menu24`, `menu25`, `menu26`, `menu27`, `menu28`, `menu29`, `menu30`, `text2`, `text3`, `text4`, `text5`, `text6`, `text7`, `text8`, `text9`, `text10`, `text11`, `text12`, `text13`, `text14`, `text15`, `text16`, `text17`, `text18`, `text19`, `text20`, `text21`, `text22`, `text23`, `text24`, `text25`, `text26`, `text27`, `text28`, `text29`, `text30`, `status`, `string`, `navigation`) VALUES
('About', '&lt;p&gt;  With RealtyScript, you can easily manage the content of this page right from the administration panel -- no code necessary! You can insert images, links, tables, and much more (like smiley faces, also known as emoticons). Try it for yourself in our demo!&lt;/p&gt;&lt;table border=&quot;1&quot; cellpadding=&quot;1&quot; cellspacing=&quot;1&quot; style=&quot;width: 100%; &quot;&gt;  &lt;tbody&gt;   &lt;tr&gt;    &lt;td&gt;     &lt;h3 style=&quot;color:blue;&quot;&gt;      This is&lt;/h3&gt;    &lt;/td&gt;    &lt;td&gt;     &lt;h3 style=&quot;color:blue;&quot;&gt;      just a test!&lt;/h3&gt;    &lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;    &lt;td&gt;     &lt;a href=&quot;http://realtyscript.com&quot;&gt;Test Link to RealtyScript&lt;/a&gt;&lt;/td&gt;    &lt;td&gt;     &lt;a href=&quot;http://realtyscript.com&quot;&gt;Test Link to RealtyScript&lt;/a&gt;&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;    &lt;td&gt;     &lt;ul&gt;      &lt;li&gt;       Content&lt;/li&gt;     &lt;/ul&gt;    &lt;/td&gt;    &lt;td&gt;     &lt;ul&gt;      &lt;li&gt;       here&lt;/li&gt;     &lt;/ul&gt;    &lt;/td&gt;   &lt;/tr&gt;  &lt;/tbody&gt; &lt;/table&gt; &lt;p&gt;   &lt;/p&gt; &lt;p&gt;You can even easily add videos to your page: &lt;/p&gt; &lt;p&gt;  &lt;iframe allowfullscreen=&quot;&quot; frameborder=&quot;0&quot; height=&quot;315&quot; src=&quot;//www.youtube.com/embed/koNSa_6Fd1U&quot; width=&quot;560&quot;&gt;&lt;/iframe&gt;&lt;/p&gt;', '2013-07-12 00:00:00', 2, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', 'about', '1'),
('News', 'These pages are completely customizable right from the administration panel in an easy-to-use WYSIWYG style editor. This could be your company news&#039; page or it could be something else entirely.  &lt;br /&gt;&lt;br /&gt; You can also easily embed various pieces of news and other content, such as a real estate news widget:  &lt;br /&gt;&lt;br /&gt; &lt;div id=&quot;re-news-large-iframe-widget-container&quot; style=&quot;width:100%;height:50%;border: 1px solid #000000;padding:0;margin:0;font:normal normal normal 8pt verdana,arial,sans-serif;text-transform:none;text-indent:0;line-height:13px;background-color:#ffffff;letter-spacing:0;color: #555;overflow:hidden;text-align:center;&quot;&gt;&lt;div id=&quot;title&quot; style=&quot;margin:4px 5px 5px 10px;text-align:left;line-height:16px;text-align:center;&quot;&gt;&lt;a href=&quot;http://www.zillow.com/blog/&quot; target=&quot;_blank&quot; style=&quot;color:#000000;font-style:normal;font-weight:bold;font-size:13px;padding:0;text-decoration:none;&quot;&gt;Real Estate News&lt;/a&gt;&lt;/div&gt;&lt;iframe src=&quot;http://www.zillow.com/widgets/feeds/RENewsWidget.htm?did=re-news-large-iframe-widget-container&amp;type=iframe&amp;size=wide&amp;cat=all&amp;textcolor=000&amp;bordercolor=000000&quot; width=&quot;100%&quot; height=&quot;250&quot; frameborder=&quot;0&quot; scrolling=&quot;no&quot; style=&quot;display:block;&quot;&gt;&lt;/iframe&gt;&lt;div id=&quot;footer-links-container&quot; style=&quot;margin:5px 5px 0;&quot;&gt;&lt;div style=&quot;font-size:10px;&quot;&gt;&lt;span id=&quot;widgetFooterLink&quot; class=&quot;regionBasedLink&quot;&gt;&lt;a target=&quot;_blank&quot; style=&quot;font:normal normal normal 10px verdana,arial,sans-serif;border:0 none;text-decoration:none;color:#000000;&quot; href=&quot;http://www.zillow.com/boston-ma/rent/&quot;&gt;&lt;span class=&quot;region&quot;&gt;Boston&lt;/span&gt; on Zillow&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt; &lt;br /&gt;&lt;br /&gt; &lt;div class=&quot;mlc-objectBox&quot; id=&quot;LatestNews&quot;&gt; &lt;script type=&quot;text/javascript&quot;&gt;toolId=&quot;LatestNews&quot;&lt;/script&gt; &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; rev=&quot;stylesheet&quot; href=&quot;http://widgets.mortgageloan.com/css/tool/GenerateCss.php?toolcolor=%23000000&amp;toolbgcolor=%23FFFFFF&amp;width=210&amp;height=180&amp;brbgcolor=%23E5E5E5&amp;bordertextcolor=%23000000&amp;toolid=LatestNews&quot; media=&quot;print,screen&quot;/&gt; &lt;h2&gt;Latest Mortgage Stories&lt;/h2&gt; &lt;iframe id=&quot;ML-Frame&quot; frameborder=&quot;no&quot; src=&quot;http://widgets.mortgageloan.com/tool/mortgage/LatestNews.html&quot; style=&quot;width:210px; height:180px;&quot; type=&quot;text/html&quot;&gt;&lt;/iframe&gt; &lt;p style=&quot;background-color: #E5E5E5; text-align:center;line-height: 15px;&quot;&gt;&lt;a style=&quot;color: #000000; display: inline; font-family: arial,verdana,tahoma,helvetica,sans-serif; font-size: 7pt; font-style: normal; font-weight: normal; text-decoration: none;&quot; href=&quot;http://www.mortgageloan.com/&quot;&gt;MortgageLoan.com&lt;/a&gt;&lt;/p&gt; &lt;/div&gt;', '2013-07-12 00:00:00', 3, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', 'news', '1'),
('Affordability Calculator', '&lt;div style=&quot;width:688px;height:752px;background-color: #fff;font: normal normal normal 8pt verdana,arial,sans-serif;line-height: 13px;margin: 0;padding: 0;overflow: hidden;text-align: center;border: 1px solid #fff;&quot;&gt;&lt;div style=&quot;height:25px;overflow:hidden;color:#fff;&quot;&gt;&lt;h5 style=&quot;margin:6px 5px 7px;color: #fff;display: block;text-align: center;&quot;&gt;&lt;a href=&quot;http://www.zillow.com/mortgage-calculator/house-affordability/&quot; target=&quot;_blank&quot; title=&quot;How Much House Can I Afford?&quot; style=&quot;font: normal normal bold 11px verdana,arial,sans-serif;line-height: 13px;text-decoration:none;color: #fff;&quot;&gt;How Much House Can I Afford?&lt;/a&gt;&lt;/h5&gt;&lt;/div&gt;&lt;iframe frameborder=&quot;0&quot; src=&quot;http://www.zillow.com/mortgage/widgets/AffordabilityCalculatorWidget.htm?inc=50000&quot; height=&quot;700px&quot; scrolling=&quot;no&quot; width=&quot;688px&quot;&gt;&lt;/iframe&gt;&lt;div style=&quot;height:25px;border:1px solid #fff;border:0px none;border-top: 0px none;text-align:center;overflow:hidden;&quot;&gt;&lt;div style=&quot;margin:6px 5px 7px;color:#fff;&quot;&gt;&lt;a href=&quot;http://www.zillow.com/mortgage-calculator/&quot; target=&quot;_blank&quot; title=&quot;Mortgage calculator&quot; style=&quot;font: normal normal normal 11px verdana,arial,sans-serif;line-height: 13px;text-decoration:none;color: #fff;&quot;&gt;How much can you afford?&lt;/a&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;', '2014-06-14 00:01:10', 5, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', 'affordibility-calculator', '0'),
('Current Mortgage Rates', '&lt;div id=&quot;large-rate-table-iframe-widget-container&quot; style=&quot;width:308px;border: 1px solid #bfbfbf;padding:12px;margin:0;font:normal normal normal 8pt verdana,arial,sans-serif;text-transform:none;text-indent:0;line-height:13px;background-color:#fff;letter-spacing:0;color: #555;overflow:hidden;text-align:center;&quot;&gt;&lt;div id=&quot;title&quot; style=&quot;margin:5px 0 12px;text-align:left;&quot;&gt;&lt;h1 style=&quot;padding-top:0px;text-align:left;font-family: Arial,verdana,sans-serif;margin:0&quot;&gt;&lt;a href=&quot;http://www.zillow.com/mortgage-rates/&quot; target=&quot;_blank&quot; style=&quot;color:#000;font-style:normal;font-weight:bold;font-size:20px;padding:0;text-decoration:none;&quot;&gt;Zillow Mortgage Marketplace&lt;/a&gt;&lt;/h1&gt;&lt;/div&gt;&lt;iframe src=&quot;http://www.zillow.com/webtools/widgets/RateTableDistributionWidget.htm?mp=RD-FLNVMXZ&amp;&quot; width=&quot;306&quot; height=&quot;215&quot; frameborder=&quot;0&quot; scrolling=&quot;no&quot; style=&quot;display:block;&quot;&gt;&lt;/iframe&gt;&lt;/div&gt;', '2014-06-16 20:25:41', 6, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', 'current-rates', '0'),
('Mortgage Calculator', '&lt;div style=&quot;width:688px;height:752px;background-color: #fff;font: normal normal normal 8pt verdana,arial,sans-serif;line-height: 13px;margin: 0;padding: 0;overflow: hidden;text-align: center;border: 1px solid #fff;&quot;&gt;&lt;div style=&quot;height:25px;overflow:hidden;color:#fff;&quot;&gt;&lt;h5 style=&quot;margin:6px 5px 7px;font-size:11px;color: #fff;display: block;text-align: center;font-weight: bold;&quot;&gt;Monthly Payment Calculator&lt;/h5&gt;&lt;/div&gt;&lt;iframe frameborder=&quot;0&quot; src=&quot;http://www.zillow.com/mortgage/MortgageCalculatorWidgetLarge.htm?homePrice=400000&quot; height=&quot;700px&quot; scrolling=&quot;no&quot; width=&quot;688px&quot;&gt;&lt;/iframe&gt;&lt;div style=&quot;height:25px;border:1px solid #fff;border:0px none;border-top: 0px none;text-align:center;overflow:hidden;&quot;&gt;&lt;div style=&quot;margin:6px 5px 7px;color:#fff;&quot;&gt;&lt;a href=&quot;http://www.zillow.com/mortgage-calculator/&quot; target=&quot;_blank&quot; title=&quot;Mortgage calculator on Zillow&quot; style=&quot;font-size:11px;font-weight:normal;text-decoration:none;color: #fff;&quot;&gt;Zillow Mortgage Calculator&lt;/a&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;', '2014-06-16 20:26:23', 7, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', 'mortgage-calculator', '0');

DROP TABLE IF EXISTS `{TABLE_PREFIX}privileges`;
CREATE TABLE `{TABLE_PREFIX}privileges` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `privilege` varchar(25) DEFAULT NULL,
  `manage_users` varchar(3) DEFAULT NULL,
  `manage_listings` varchar(3) DEFAULT NULL,
  `manage_gallery` varchar(3) DEFAULT NULL,
  `manage_types` varchar(3) DEFAULT NULL,
  `manage_settings` varchar(3) DEFAULT NULL,
  `manage_administrators` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

INSERT INTO `{TABLE_PREFIX}privileges` (`id`, `privilege`, `manage_users`, `manage_listings`, `manage_gallery`, `manage_types`, `manage_settings`, `manage_administrators`) VALUES
(1, 'Global', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES');

DROP TABLE IF EXISTS `{TABLE_PREFIX}ratings`;
CREATE TABLE `{TABLE_PREFIX}ratings` (
  `ip` text,
  `userid` int(10) unsigned DEFAULT '0',
  `rating` mediumint(8) unsigned DEFAULT '0',
  `date` date DEFAULT NULL,
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}status`;
CREATE TABLE `{TABLE_PREFIX}status` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `counter` int(10) DEFAULT '0',
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

INSERT INTO `{TABLE_PREFIX}status` (`id`, `counter`, `name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`) VALUES
(1, 0, 'Available', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 0, 'Sale Pending', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(3, 0, 'Under Agreement', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, 0, 'Sold', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, 0, 'Unavailable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `{TABLE_PREFIX}styles`;
CREATE TABLE `{TABLE_PREFIX}styles` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=25 ;

INSERT INTO `{TABLE_PREFIX}styles` (`name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `id`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`) VALUES
('Garrison', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Colonial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cape', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Contemporary', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Ranch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Raised Ranch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Split Entry', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Victorian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Tudor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Gambrel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Antique', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Farmhouse', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Saltbox', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cottage', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Bungalow', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Multi-level', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Log', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Front-to-Back Split', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Lofted Split', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Greek Revival', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Shingle', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Other', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `{TABLE_PREFIX}types`;
CREATE TABLE `{TABLE_PREFIX}types` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `counter` int(10) unsigned NOT NULL DEFAULT '0',
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ;

INSERT INTO `{TABLE_PREFIX}types` (`name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `counter`, `id`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`) VALUES
('Single Family Home', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4294967295, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Condo / Townhouse / Co-op', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Multi-Family Home', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mfd / Mobile Home', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Land', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Farms', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Rentals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `{TABLE_PREFIX}types2`;
CREATE TABLE `{TABLE_PREFIX}types2` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `name3` varchar(50) DEFAULT NULL,
  `name4` varchar(50) DEFAULT NULL,
  `name5` varchar(50) DEFAULT NULL,
  `name6` varchar(50) DEFAULT NULL,
  `name7` varchar(50) DEFAULT NULL,
  `name8` varchar(50) DEFAULT NULL,
  `name9` varchar(50) DEFAULT NULL,
  `name10` varchar(50) DEFAULT NULL,
  `name11` varchar(50) DEFAULT NULL,
  `name12` varchar(50) DEFAULT NULL,
  `name13` varchar(50) DEFAULT NULL,
  `name14` varchar(50) DEFAULT NULL,
  `name15` varchar(50) DEFAULT NULL,
  `name16` varchar(50) DEFAULT NULL,
  `name17` varchar(50) DEFAULT NULL,
  `name18` varchar(50) DEFAULT NULL,
  `name19` varchar(50) DEFAULT NULL,
  `name20` varchar(50) DEFAULT NULL,
  `name21` varchar(50) DEFAULT NULL,
  `name22` varchar(50) DEFAULT NULL,
  `name23` varchar(50) DEFAULT NULL,
  `name24` varchar(50) DEFAULT NULL,
  `name25` varchar(50) DEFAULT NULL,
  `name26` varchar(50) DEFAULT NULL,
  `name27` varchar(50) DEFAULT NULL,
  `name28` varchar(50) DEFAULT NULL,
  `name29` varchar(50) DEFAULT NULL,
  `name30` varchar(50) DEFAULT NULL,
  `class` varchar(31) NOT NULL DEFAULT 'sale',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

INSERT INTO `{TABLE_PREFIX}types2` (`name`, `name2`, `name3`, `name4`, `name5`, `name6`, `name7`, `name8`, `name9`, `name10`, `name11`, `name12`, `id`, `name13`, `name14`, `name15`, `name16`, `name17`, `name18`, `name19`, `name20`, `name21`, `name22`, `name23`, `name24`, `name25`, `name26`, `name27`, `name28`, `name29`, `name30`, `class`) VALUES
('For Sale / Residential', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sale'),
('For Rent / Residential', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'monthly'),
('For Sale / Commercial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sale'),
('For Rent / Commercial', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'monthly');

DROP TABLE IF EXISTS `{TABLE_PREFIX}users`;
CREATE TABLE `{TABLE_PREFIX}users` (
  `u_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `approved` tinyint(1) unsigned DEFAULT '0',
  `package` int(10) unsigned DEFAULT '0',
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `description` text,
  `zip` varchar(20) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `location_1` int(5) NOT NULL,
  `location_2` int(5) NOT NULL,
  `location_3` int(5) NOT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `fax` varchar(50) DEFAULT NULL,
  `mobile` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `rating` mediumint(8) unsigned DEFAULT '0',
  `votes` mediumint(8) unsigned DEFAULT '0',
  `date_added` date DEFAULT NULL,
  `date_updated` date DEFAULT NULL,
  `date_upgraded` date DEFAULT NULL,
  `ip_added` text,
  `ip_updated` text,
  `ip_upgraded` text,
  `number` varchar(255) DEFAULT NULL,
  `login` varchar(50) DEFAULT NULL,
  `password` varchar(32) DEFAULT NULL,
  `hits` int(5) unsigned DEFAULT '0',
  `image` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`u_id`),
  FULLTEXT KEY `description` (`description`),
  FULLTEXT KEY `all_fields` (`first_name`,`last_name`,`company_name`,`description`,`address`),
  FULLTEXT KEY `personal` (`first_name`,`last_name`,`company_name`,`address`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}values`;
CREATE TABLE `{TABLE_PREFIX}values` (
  `id` mediumint(5) NOT NULL AUTO_INCREMENT,
  `f_id` mediumint(5) NOT NULL,
  `name` varchar(255) NOT NULL,
  `name2` varchar(255) NOT NULL,
  `name3` varchar(255) NOT NULL,
  `name4` varchar(255) NOT NULL,
  `name5` varchar(255) NOT NULL,
  `name6` varchar(255) NOT NULL,
  `name7` varchar(255) NOT NULL,
  `name8` varchar(255) NOT NULL,
  `name9` varchar(255) NOT NULL,
  `name10` varchar(255) NOT NULL,
  `name11` varchar(255) NOT NULL,
  `name12` varchar(255) NOT NULL,
  `name13` varchar(255) NOT NULL,
  `name14` varchar(255) NOT NULL,
  `name15` varchar(255) NOT NULL,
  `name16` varchar(255) NOT NULL,
  `name17` varchar(255) NOT NULL,
  `name18` varchar(255) NOT NULL,
  `name19` varchar(255) NOT NULL,
  `name20` varchar(255) NOT NULL,
  `name21` varchar(255) NOT NULL,
  `name22` varchar(255) NOT NULL,
  `name23` varchar(255) NOT NULL,
  `name24` varchar(255) NOT NULL,
  `name25` varchar(255) NOT NULL,
  `name26` varchar(255) NOT NULL,
  `name27` varchar(255) NOT NULL,
  `name28` varchar(255) NOT NULL,
  `name29` varchar(255) NOT NULL,
  `name30` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `{TABLE_PREFIX}zip`;
CREATE TABLE `{TABLE_PREFIX}zip` (
  `zip` varchar(10) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(3) DEFAULT NULL,
  `county` varchar(255) DEFAULT NULL,
  `latitude` varchar(255) DEFAULT NULL,
  `longitude` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;